version: "3.8"

services:
  php-fpm-symfony-rest-api:
    container_name: php-fpm-symfony-rest-api
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=wallet-clean-architecture"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx-symfony-rest-api:
    container_name: nginx-symfony-rest-api
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm-symfony-rest-api

  postgres-symfony-rest-api:
    container_name: postgres-symfony-rest-api
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
